package com.jarvis.mapper.entities;

public class Book extends BasicEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.ISBN
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.TITLE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.AUTHOR
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.DESCRIPTION
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.READER_USERNAME
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String readerUsername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.ID
     *
     * @return the value of book.ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.ID
     *
     * @param id the value for book.ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.ISBN
     *
     * @return the value of book.ISBN
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.ISBN
     *
     * @param isbn the value for book.ISBN
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.TITLE
     *
     * @return the value of book.TITLE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.TITLE
     *
     * @param title the value for book.TITLE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.AUTHOR
     *
     * @return the value of book.AUTHOR
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.AUTHOR
     *
     * @param author the value for book.AUTHOR
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.DESCRIPTION
     *
     * @return the value of book.DESCRIPTION
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.DESCRIPTION
     *
     * @param description the value for book.DESCRIPTION
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.READER_USERNAME
     *
     * @return the value of book.READER_USERNAME
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getReaderUsername() {
        return readerUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.READER_USERNAME
     *
     * @param readerUsername the value for book.READER_USERNAME
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setReaderUsername(String readerUsername) {
        this.readerUsername = readerUsername == null ? null : readerUsername.trim();
    }
}