package com.jarvis.mapper.entities;

import java.util.Date;

public class LocFiles extends BasicEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_files.id
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_files.name
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_files.root_path
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String rootPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_files.full_path
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String fullPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_files.create_date
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_files.sync_date
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Date syncDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_files.id
     *
     * @return the value of loc_files.id
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_files.id
     *
     * @param id the value for loc_files.id
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_files.name
     *
     * @return the value of loc_files.name
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_files.name
     *
     * @param name the value for loc_files.name
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_files.root_path
     *
     * @return the value of loc_files.root_path
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getRootPath() {
        return rootPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_files.root_path
     *
     * @param rootPath the value for loc_files.root_path
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setRootPath(String rootPath) {
        this.rootPath = rootPath == null ? null : rootPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_files.full_path
     *
     * @return the value of loc_files.full_path
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getFullPath() {
        return fullPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_files.full_path
     *
     * @param fullPath the value for loc_files.full_path
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setFullPath(String fullPath) {
        this.fullPath = fullPath == null ? null : fullPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_files.create_date
     *
     * @return the value of loc_files.create_date
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_files.create_date
     *
     * @param createDate the value for loc_files.create_date
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_files.sync_date
     *
     * @return the value of loc_files.sync_date
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Date getSyncDate() {
        return syncDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_files.sync_date
     *
     * @param syncDate the value for loc_files.sync_date
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setSyncDate(Date syncDate) {
        this.syncDate = syncDate;
    }
}