package com.jarvis.mapper.entities;

import java.util.Date;

public class Privileges extends BasicEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.PRIVILEGE_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Integer privilegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.OPERATION
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.COMPONENT
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.DESCRIPTION
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.EFFECTIVE_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Date effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.EXPIRED_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Date expiredDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.STATUS_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Integer statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.INSERT_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Date insertDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileges.MOD_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String modDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.PRIVILEGE_ID
     *
     * @return the value of privileges.PRIVILEGE_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.PRIVILEGE_ID
     *
     * @param privilegeId the value for privileges.PRIVILEGE_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.OPERATION
     *
     * @return the value of privileges.OPERATION
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.OPERATION
     *
     * @param operation the value for privileges.OPERATION
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.COMPONENT
     *
     * @return the value of privileges.COMPONENT
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.COMPONENT
     *
     * @param component the value for privileges.COMPONENT
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.DESCRIPTION
     *
     * @return the value of privileges.DESCRIPTION
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.DESCRIPTION
     *
     * @param description the value for privileges.DESCRIPTION
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.EFFECTIVE_DATE
     *
     * @return the value of privileges.EFFECTIVE_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for privileges.EFFECTIVE_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.EXPIRED_DATE
     *
     * @return the value of privileges.EXPIRED_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Date getExpiredDate() {
        return expiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.EXPIRED_DATE
     *
     * @param expiredDate the value for privileges.EXPIRED_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setExpiredDate(Date expiredDate) {
        this.expiredDate = expiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.STATUS_ID
     *
     * @return the value of privileges.STATUS_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.STATUS_ID
     *
     * @param statusId the value for privileges.STATUS_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.INSERT_DATE
     *
     * @return the value of privileges.INSERT_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.INSERT_DATE
     *
     * @param insertDate the value for privileges.INSERT_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileges.MOD_DATE
     *
     * @return the value of privileges.MOD_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getModDate() {
        return modDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileges.MOD_DATE
     *
     * @param modDate the value for privileges.MOD_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setModDate(String modDate) {
        this.modDate = modDate == null ? null : modDate.trim();
    }
}