package com.jarvis.mapper.entities;

public class Reader extends BasicEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column READER.USERNAME
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column READER.PASSWORD
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column READER.FULLNAME
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    private String fullname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column READER.USERNAME
     *
     * @return the value of READER.USERNAME
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column READER.USERNAME
     *
     * @param username the value for READER.USERNAME
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column READER.PASSWORD
     *
     * @return the value of READER.PASSWORD
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column READER.PASSWORD
     *
     * @param password the value for READER.PASSWORD
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column READER.FULLNAME
     *
     * @return the value of READER.FULLNAME
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column READER.FULLNAME
     *
     * @param fullname the value for READER.FULLNAME
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }
}