package com.jarvis.mapper.entities;

public class RolePrivilegesKey extends BasicEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_privileges.ROLE_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_privileges.PRIVILEGE_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Integer privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_privileges.ROLE_ID
     *
     * @return the value of role_privileges.ROLE_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_privileges.ROLE_ID
     *
     * @param roleId the value for role_privileges.ROLE_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_privileges.PRIVILEGE_ID
     *
     * @return the value of role_privileges.PRIVILEGE_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_privileges.PRIVILEGE_ID
     *
     * @param privilegeId the value for role_privileges.PRIVILEGE_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }
}