package com.jarvis.mapper.entities;

import java.util.Date;

public class Status extends BasicEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.STATUS_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Integer statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.DESCRIPTION
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.COMPONENT
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.INSERT_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Date insertDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.STATUS_ID
     *
     * @return the value of status.STATUS_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.STATUS_ID
     *
     * @param statusId the value for status.STATUS_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.DESCRIPTION
     *
     * @return the value of status.DESCRIPTION
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.DESCRIPTION
     *
     * @param description the value for status.DESCRIPTION
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.COMPONENT
     *
     * @return the value of status.COMPONENT
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.COMPONENT
     *
     * @param component the value for status.COMPONENT
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.INSERT_DATE
     *
     * @return the value of status.INSERT_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.INSERT_DATE
     *
     * @param insertDate the value for status.INSERT_DATE
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }
}