package com.jarvis.mapper.entities;

public class TransactionUsers extends TransactionUsersKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_USERS.USER_ID
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_USERS.USER_ID
     *
     * @return the value of TRANSACTION_USERS.USER_ID
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_USERS.USER_ID
     *
     * @param userId the value for TRANSACTION_USERS.USER_ID
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}