package com.jarvis.mapper.entities;

public class TransactionUsersKey extends BasicEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_USERS.TRX_ID
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    private Integer trxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_USERS.SEQ_ID
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    private String seqId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_USERS.TRX_ID
     *
     * @return the value of TRANSACTION_USERS.TRX_ID
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public Integer getTrxId() {
        return trxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_USERS.TRX_ID
     *
     * @param trxId the value for TRANSACTION_USERS.TRX_ID
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public void setTrxId(Integer trxId) {
        this.trxId = trxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_USERS.SEQ_ID
     *
     * @return the value of TRANSACTION_USERS.SEQ_ID
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public String getSeqId() {
        return seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_USERS.SEQ_ID
     *
     * @param seqId the value for TRANSACTION_USERS.SEQ_ID
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public void setSeqId(String seqId) {
        this.seqId = seqId == null ? null : seqId.trim();
    }
}