package com.jarvis.mapper.entities;

public class UserTrxHisKey extends BasicEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TRX_HIS.TRX_ID
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    private Integer trxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TRX_HIS.SEQ_ID
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    private Integer seqId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TRX_HIS.TRX_ID
     *
     * @return the value of USER_TRX_HIS.TRX_ID
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public Integer getTrxId() {
        return trxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TRX_HIS.TRX_ID
     *
     * @param trxId the value for USER_TRX_HIS.TRX_ID
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public void setTrxId(Integer trxId) {
        this.trxId = trxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TRX_HIS.SEQ_ID
     *
     * @return the value of USER_TRX_HIS.SEQ_ID
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public Integer getSeqId() {
        return seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TRX_HIS.SEQ_ID
     *
     * @param seqId the value for USER_TRX_HIS.SEQ_ID
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    public void setSeqId(Integer seqId) {
        this.seqId = seqId;
    }
}