package com.jarvis.mapper.entities;

public class UserTrxHisKey extends BasicEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_trx_his.TRX_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Integer trxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_trx_his.SEQ_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    private Integer seqId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_trx_his.TRX_ID
     *
     * @return the value of user_trx_his.TRX_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Integer getTrxId() {
        return trxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_trx_his.TRX_ID
     *
     * @param trxId the value for user_trx_his.TRX_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setTrxId(Integer trxId) {
        this.trxId = trxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_trx_his.SEQ_ID
     *
     * @return the value of user_trx_his.SEQ_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public Integer getSeqId() {
        return seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_trx_his.SEQ_ID
     *
     * @param seqId the value for user_trx_his.SEQ_ID
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    public void setSeqId(Integer seqId) {
        this.seqId = seqId;
    }
}