error:
  whitelabel:
    enabled: false

amazon:
  associate_id: habuma-20

logging:
  level:
    root: INFO


spring:
    datasource:
        name: jarvis_db
        url: jdbc:mysql://localhost:3306/jarvis_db
        username: jarvis_db
        password: mYsqL$%123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 30
        initialSize: 10
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 30

mybatis:
  mapperLocations: classpath:com/jarvis/mapper/xml/*.xml
  typeAliasesPackage: com.jarvis.mapper