package jarvis.file.sync.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import jarvis.file.sync.mapper.entities.LocFiles;
import jarvis.file.sync.mapper.entities.LocFilesExample;

public interface LocFilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_files
     *
     * @mbg.generated Wed Feb 08 22:23:10 CST 2017
     */
    long countByExample(LocFilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_files
     *
     * @mbg.generated Wed Feb 08 22:23:10 CST 2017
     */
    int deleteByExample(LocFilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_files
     *
     * @mbg.generated Wed Feb 08 22:23:10 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_files
     *
     * @mbg.generated Wed Feb 08 22:23:10 CST 2017
     */
    int insert(LocFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_files
     *
     * @mbg.generated Wed Feb 08 22:23:10 CST 2017
     */
    int insertSelective(LocFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_files
     *
     * @mbg.generated Wed Feb 08 22:23:10 CST 2017
     */
    List<LocFiles> selectByExample(LocFilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_files
     *
     * @mbg.generated Wed Feb 08 22:23:10 CST 2017
     */
    LocFiles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_files
     *
     * @mbg.generated Wed Feb 08 22:23:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") LocFiles record, @Param("example") LocFilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_files
     *
     * @mbg.generated Wed Feb 08 22:23:10 CST 2017
     */
    int updateByExample(@Param("record") LocFiles record, @Param("example") LocFilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_files
     *
     * @mbg.generated Wed Feb 08 22:23:10 CST 2017
     */
    int updateByPrimaryKeySelective(LocFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_files
     *
     * @mbg.generated Wed Feb 08 22:23:10 CST 2017
     */
    int updateByPrimaryKey(LocFiles record);
}