CREATE OR REPLACE VIEW V_USER_INFO AS
  SELECT
    U.USER_ID,
    U.LOGIN_NAME,
    R.ROLE_NAME,
    UT.TYPE_NAME
  FROM USERS U, ROLE R, USER_TYPES UT
  WHERE U.USER_ROLE_ID = R.ROLE_ID
        AND R.USER_TYPE_ID = UT.USER_TYPE_ID;

CREATE OR REPLACE VIEW V_USER_INFO_1 AS
  SELECT
    U.USER_ID,
    U.LOGIN_NAME,
    R.ROLE_NAME,
    UT.TYPE_NAME
  FROM USERS U, ROLE R, USER_TYPES UT
  WHERE U.USER_ROLE_ID = R.ROLE_ID
        AND R.USER_TYPE_ID = UT.USER_TYPE_ID;