CREATE TABLE IF NOT EXISTS RESOURCE_ROLE (
  ID          INT         NOT NULL,
  DESCRIPTION VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS KNOWLEDGE_LEVEL (
  ID         INT          NOT NULL,
  CODE       VARCHAR(1)   NOT NULL,
  SHORT_DESC VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;


CREATE TABLE IF NOT EXISTS KNOWLEDGE_DOMAIN (
  DOMAIN_ID        INT          NOT NULL,
  PARENT_DOMAIN_ID INT          NOT NULL,
  CODE             VARCHAR(50)  NOT NULL,
  SHORT_DESC       VARCHAR(200) NOT NULL,
  PRIMARY KEY (DOMAIN_ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;


CREATE TABLE IF NOT EXISTS KNOWLEDGE (
  KNOWLEDGE_ID INT          NOT NULL,
  DOMAIN_ID    INT          NOT NULL,
  SKILL_DESC   VARCHAR(200) NOT NULL,
  PRIMARY KEY (KNOWLEDGE_ID),
  INDEX FK_KNOWLEDGE_DOMAIN_ID_IDX (DOMAIN_ID ASC),
  CONSTRAINT FK_KNOWLEDGE_DOMAIN_ID
  FOREIGN KEY (DOMAIN_ID)
  REFERENCES KNOWLEDGE_DOMAIN (DOMAIN_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS RESOURCES (
  XEROX_CID    VARCHAR(20) NOT NULL,
  COGNIZANT_ID VARCHAR(45) NOT NULL,
  NAME         VARCHAR(45) NOT NULL,
  ROLE_ID      INT         NOT NULL,
  PRIMARY KEY (XEROX_CID),
  INDEX FK_ROLE_ID_IDX (ROLE_ID ASC),
  CONSTRAINT FK_ROLE_ID
  FOREIGN KEY (ROLE_ID)
  REFERENCES RESOURCE_ROLE (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS RESOURCE_KNOWLEDGE (
  RESOURCE_ID        VARCHAR(20) NOT NULL
  COMMENT '	',
  KNOWLEDGE_ID       INT         NOT NULL,
  KNOWLEDGE_LEVEL_ID INT         NOT NULL,
  PRIMARY KEY (RESOURCE_ID),
  INDEX FK_SKILL_ID_IDX (KNOWLEDGE_ID ASC),
  INDEX FK_SKILL_LEVEL_ID_IDX (KNOWLEDGE_LEVEL_ID ASC),
  CONSTRAINT FK_RESOURCE_ID
  FOREIGN KEY (RESOURCE_ID)
  REFERENCES RESOURCES (XEROX_CID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_KNOWLEDGE_ID
  FOREIGN KEY (KNOWLEDGE_ID)
  REFERENCES KNOWLEDGE (KNOWLEDGE_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_KNOWLEDGE_LEVEL_ID
  FOREIGN KEY (KNOWLEDGE_LEVEL_ID)
  REFERENCES KNOWLEDGE_LEVEL (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;