INSERT INTO USER_TYPES VALUES (0,'SUPER','SUPER ADMIN',NOW());
INSERT INTO ROLE VALUES (0,'SUPER ROLE','SUPER ROLE ',0,11,NOW(),NOW());
INSERT INTO USERS VALUES (0,'ADMIN','ADMIN','ADMIN',NOW(),'ADMIN','','',0,1,0,NOW());