package com.jarvis.mapper.module;

import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.USER_ID
     *
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.LOGIN_NAME
     *
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.FIRST_NAME
     *
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.LAST_NAME
     *
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.EFFECTIVE_DATE
     *
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    private Date effectiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.PASSWORD
     *
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.PASSWORD1
     *
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    private String password1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.PASSWORD2
     *
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    private String password2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.BAD_PWD_CNT
     *
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    private String badPwdCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.USER_STATUS_ID
     *
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    private Integer userStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.USER_ROLE_ID
     *
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    private Integer userRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.INSERT_DATE
     *
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    private Date insertDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.USER_ID
     *
     * @return the value of USERS.USER_ID
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.USER_ID
     *
     * @param userId the value for USERS.USER_ID
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.LOGIN_NAME
     *
     * @return the value of USERS.LOGIN_NAME
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.LOGIN_NAME
     *
     * @param loginName the value for USERS.LOGIN_NAME
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.FIRST_NAME
     *
     * @return the value of USERS.FIRST_NAME
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.FIRST_NAME
     *
     * @param firstName the value for USERS.FIRST_NAME
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.LAST_NAME
     *
     * @return the value of USERS.LAST_NAME
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.LAST_NAME
     *
     * @param lastName the value for USERS.LAST_NAME
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.EFFECTIVE_DATE
     *
     * @return the value of USERS.EFFECTIVE_DATE
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for USERS.EFFECTIVE_DATE
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.PASSWORD
     *
     * @return the value of USERS.PASSWORD
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.PASSWORD
     *
     * @param password the value for USERS.PASSWORD
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.PASSWORD1
     *
     * @return the value of USERS.PASSWORD1
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public String getPassword1() {
        return password1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.PASSWORD1
     *
     * @param password1 the value for USERS.PASSWORD1
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public void setPassword1(String password1) {
        this.password1 = password1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.PASSWORD2
     *
     * @return the value of USERS.PASSWORD2
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public String getPassword2() {
        return password2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.PASSWORD2
     *
     * @param password2 the value for USERS.PASSWORD2
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public void setPassword2(String password2) {
        this.password2 = password2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.BAD_PWD_CNT
     *
     * @return the value of USERS.BAD_PWD_CNT
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public String getBadPwdCnt() {
        return badPwdCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.BAD_PWD_CNT
     *
     * @param badPwdCnt the value for USERS.BAD_PWD_CNT
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public void setBadPwdCnt(String badPwdCnt) {
        this.badPwdCnt = badPwdCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.USER_STATUS_ID
     *
     * @return the value of USERS.USER_STATUS_ID
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public Integer getUserStatusId() {
        return userStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.USER_STATUS_ID
     *
     * @param userStatusId the value for USERS.USER_STATUS_ID
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public void setUserStatusId(Integer userStatusId) {
        this.userStatusId = userStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.USER_ROLE_ID
     *
     * @return the value of USERS.USER_ROLE_ID
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public Integer getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.USER_ROLE_ID
     *
     * @param userRoleId the value for USERS.USER_ROLE_ID
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.INSERT_DATE
     *
     * @return the value of USERS.INSERT_DATE
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.INSERT_DATE
     *
     * @param insertDate the value for USERS.INSERT_DATE
     * @mbg.generated Sun Feb 05 15:59:12 CST 2017
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }
}