package com.jarvis.mapper;

import com.jarvis.mapper.entities.Files;
import com.jarvis.mapper.entities.FilesExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    long countByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    int deleteByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    int insert(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    int insertSelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    List<Files> selectByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    Files selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") Files record, @Param("example") FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    int updateByExample(@Param("record") Files record, @Param("example") FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    int updateByPrimaryKeySelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Wed Feb 08 21:28:42 CST 2017
     */
    int updateByPrimaryKey(Files record);
}