package com.jarvis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jarvis.mapper.entities.Privileges;
import com.jarvis.mapper.entities.PrivilegesExample;

public interface PrivilegesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    long countByExample(PrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int deleteByExample(PrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int deleteByPrimaryKey(Integer privilegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int insert(Privileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int insertSelective(Privileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    List<Privileges> selectByExample(PrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    Privileges selectByPrimaryKey(Integer privilegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") Privileges record, @Param("example") PrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int updateByExample(@Param("record") Privileges record, @Param("example") PrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int updateByPrimaryKeySelective(Privileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privileges
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int updateByPrimaryKey(Privileges record);
}