package com.jarvis.mapper;

import com.jarvis.mapper.entities.TransactionType;
import com.jarvis.mapper.entities.TransactionTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_type
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    long countByExample(TransactionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_type
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int deleteByExample(TransactionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_type
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int deleteByPrimaryKey(Integer trxTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_type
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int insert(TransactionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_type
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int insertSelective(TransactionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_type
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    List<TransactionType> selectByExample(TransactionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_type
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    TransactionType selectByPrimaryKey(Integer trxTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_type
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") TransactionType record, @Param("example") TransactionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_type
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int updateByExample(@Param("record") TransactionType record, @Param("example") TransactionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_type
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int updateByPrimaryKeySelective(TransactionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_type
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int updateByPrimaryKey(TransactionType record);
}