package com.jarvis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jarvis.mapper.entities.TransactionUsers;
import com.jarvis.mapper.entities.TransactionUsersExample;
import com.jarvis.mapper.entities.TransactionUsersKey;

public interface TransactionUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_users
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    long countByExample(TransactionUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_users
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int deleteByExample(TransactionUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_users
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int deleteByPrimaryKey(TransactionUsersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_users
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int insert(TransactionUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_users
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int insertSelective(TransactionUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_users
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    List<TransactionUsers> selectByExample(TransactionUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_users
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    TransactionUsers selectByPrimaryKey(TransactionUsersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_users
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") TransactionUsers record, @Param("example") TransactionUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_users
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int updateByExample(@Param("record") TransactionUsers record, @Param("example") TransactionUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_users
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int updateByPrimaryKeySelective(TransactionUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_users
     *
     * @mbg.generated Wed Feb 08 22:28:51 CST 2017
     */
    int updateByPrimaryKey(TransactionUsers record);
}