package com.jarvis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jarvis.mapper.entities.Reader;
import com.jarvis.mapper.entities.ReaderExample;

public interface ReaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table READER
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    long countByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table READER
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    int deleteByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table READER
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table READER
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    int insert(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table READER
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    int insertSelective(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table READER
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    List<Reader> selectByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table READER
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    Reader selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table READER
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") Reader record, @Param("example") ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table READER
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    int updateByExample(@Param("record") Reader record, @Param("example") ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table READER
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    int updateByPrimaryKeySelective(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table READER
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    int updateByPrimaryKey(Reader record);
}