package com.jarvis.mapper;

import com.jarvis.mapper.module.Status;
import com.jarvis.mapper.module.StatusExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATUS
     *
     * @mbg.generated Sun Feb 05 16:16:59 CST 2017
     */
    long countByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATUS
     *
     * @mbg.generated Sun Feb 05 16:16:59 CST 2017
     */
    int deleteByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATUS
     *
     * @mbg.generated Sun Feb 05 16:16:59 CST 2017
     */
    int deleteByPrimaryKey(Integer statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATUS
     *
     * @mbg.generated Sun Feb 05 16:16:59 CST 2017
     */
    int insert(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATUS
     *
     * @mbg.generated Sun Feb 05 16:16:59 CST 2017
     */
    int insertSelective(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATUS
     *
     * @mbg.generated Sun Feb 05 16:16:59 CST 2017
     */
    List<Status> selectByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATUS
     *
     * @mbg.generated Sun Feb 05 16:16:59 CST 2017
     */
    Status selectByPrimaryKey(Integer statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATUS
     *
     * @mbg.generated Sun Feb 05 16:16:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") Status record, @Param("example") StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATUS
     *
     * @mbg.generated Sun Feb 05 16:16:59 CST 2017
     */
    int updateByExample(@Param("record") Status record, @Param("example") StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATUS
     *
     * @mbg.generated Sun Feb 05 16:16:59 CST 2017
     */
    int updateByPrimaryKeySelective(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATUS
     *
     * @mbg.generated Sun Feb 05 16:16:59 CST 2017
     */
    int updateByPrimaryKey(Status record);
}