package com.jarvis.mapper.entities;

import java.util.Date;

public class Privileges extends BasicEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVILEGES.PRIVILEGE_ID
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    private Integer privilegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVILEGES.OPERATION
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVILEGES.COMPONENT
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    private String component;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVILEGES.DESCRIPTION
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVILEGES.EFFECTIVE_DATE
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    private Date effectiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVILEGES.EXPIRED_DATE
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    private Date expiredDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVILEGES.STATUS_ID
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVILEGES.INSERT_DATE
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    private Date insertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVILEGES.MOD_DATE
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    private String modDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVILEGES.PRIVILEGE_ID
     *
     * @return the value of PRIVILEGES.PRIVILEGE_ID
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVILEGES.PRIVILEGE_ID
     *
     * @param privilegeId the value for PRIVILEGES.PRIVILEGE_ID
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVILEGES.OPERATION
     *
     * @return the value of PRIVILEGES.OPERATION
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVILEGES.OPERATION
     *
     * @param operation the value for PRIVILEGES.OPERATION
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVILEGES.COMPONENT
     *
     * @return the value of PRIVILEGES.COMPONENT
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVILEGES.COMPONENT
     *
     * @param component the value for PRIVILEGES.COMPONENT
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVILEGES.DESCRIPTION
     *
     * @return the value of PRIVILEGES.DESCRIPTION
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVILEGES.DESCRIPTION
     *
     * @param description the value for PRIVILEGES.DESCRIPTION
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVILEGES.EFFECTIVE_DATE
     *
     * @return the value of PRIVILEGES.EFFECTIVE_DATE
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVILEGES.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for PRIVILEGES.EFFECTIVE_DATE
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVILEGES.EXPIRED_DATE
     *
     * @return the value of PRIVILEGES.EXPIRED_DATE
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public Date getExpiredDate() {
        return expiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVILEGES.EXPIRED_DATE
     *
     * @param expiredDate the value for PRIVILEGES.EXPIRED_DATE
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public void setExpiredDate(Date expiredDate) {
        this.expiredDate = expiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVILEGES.STATUS_ID
     *
     * @return the value of PRIVILEGES.STATUS_ID
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVILEGES.STATUS_ID
     *
     * @param statusId the value for PRIVILEGES.STATUS_ID
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVILEGES.INSERT_DATE
     *
     * @return the value of PRIVILEGES.INSERT_DATE
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVILEGES.INSERT_DATE
     *
     * @param insertDate the value for PRIVILEGES.INSERT_DATE
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVILEGES.MOD_DATE
     *
     * @return the value of PRIVILEGES.MOD_DATE
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public String getModDate() {
        return modDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVILEGES.MOD_DATE
     *
     * @param modDate the value for PRIVILEGES.MOD_DATE
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public void setModDate(String modDate) {
        this.modDate = modDate == null ? null : modDate.trim();
    }
}