package com.jarvis.mapper.entities;

public class Reader extends BasicEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.USERNAME
     *
     * @mbg.generated Mon Feb 06 13:32:10 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.PASSWORD
     *
     * @mbg.generated Mon Feb 06 13:32:10 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.FULLNAME
     *
     * @mbg.generated Mon Feb 06 13:32:10 CST 2017
     */
    private String fullname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.USERNAME
     *
     * @return the value of reader.USERNAME
     *
     * @mbg.generated Mon Feb 06 13:32:10 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.USERNAME
     *
     * @param username the value for reader.USERNAME
     *
     * @mbg.generated Mon Feb 06 13:32:10 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.PASSWORD
     *
     * @return the value of reader.PASSWORD
     *
     * @mbg.generated Mon Feb 06 13:32:10 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.PASSWORD
     *
     * @param password the value for reader.PASSWORD
     *
     * @mbg.generated Mon Feb 06 13:32:10 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.FULLNAME
     *
     * @return the value of reader.FULLNAME
     *
     * @mbg.generated Mon Feb 06 13:32:10 CST 2017
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.FULLNAME
     *
     * @param fullname the value for reader.FULLNAME
     *
     * @mbg.generated Mon Feb 06 13:32:10 CST 2017
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }
}