package com.jarvis.mapper.entities;

public class RolePrivilegesKey extends BasicEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_PRIVILEGES.ROLE_ID
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_PRIVILEGES.PRIVILEGE_ID
     *
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    private Integer privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_PRIVILEGES.ROLE_ID
     *
     * @return the value of ROLE_PRIVILEGES.ROLE_ID
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_PRIVILEGES.ROLE_ID
     *
     * @param roleId the value for ROLE_PRIVILEGES.ROLE_ID
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_PRIVILEGES.PRIVILEGE_ID
     *
     * @return the value of ROLE_PRIVILEGES.PRIVILEGE_ID
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_PRIVILEGES.PRIVILEGE_ID
     *
     * @param privilegeId the value for ROLE_PRIVILEGES.PRIVILEGE_ID
     * @mbg.generated Mon Feb 06 21:34:51 CST 2017
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }
}